### ISSUE TITLE
Python 2.7.x supported?

### ISSUE THREAD

**Issue by kirsn** [boxed/hammett#6]
I came across your article: https://kodare.net/2020/05/19/python-is-slow-does-not-have-to-be.html, and decided to try `hammett`. 
Am on _Python 2.7.18_

I see this when I run `python -m hammett` from within my project folder:
```
Traceback (most recent call last):
  File "D:\programs\open\python27\lib\runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "D:\programs\open\python27\lib\runpy.py", line 111, in _get_module_details
    __import__(mod_name)  # Do not catch exceptions initializing package
  File "D:\programs\open\python27\lib\site-packages\hammett\__init__.py", line 26
    _orig_print = print
                      ^
SyntaxError: invalid syntax
```

Would you have any suggestions?

**Comment by boxed** [comment]
The suggestion is to move to python 3. Python 2 is end of life. I have an article about that too: https://kodare.net/2018/02/09/moving-a-large-and-old-codebase-to-python3.html

**Comment by kirsn** [comment]
Yep, I had read that article too :). In any case, will try this out on Python 3.
